export const PARSING_CONFIG = {
  PRIORITY_KEYWORDS: {
    high: [
      'urgent',
      'important',
      'asap',
      'critical',
      'major',
      'high priority',
      'emergency',
    ],
    medium: ['medium', 'normal', 'regular'],
    low: ['low', 'minor', 'whenever', 'low priority', 'optional'],
  },

  CATEGORY_KEYWORDS: {
    work: [
      'meeting',
      'presentation',
      'report',
      'project',
      'deadline',
      'client',
      'office',
      'conference',
      'email',
      'call',
      'review',
      'proposal',
      'budget',
      'team',
      'manager',
      'colleague',
      'business',
      'professional',
      'work',
      'job',
      'career',
      'interview',
      'resume',
      'salary',
      'promotion',
      'training',
      'workshop',
      'seminar',
    ],
    personal: [
      'grocery',
      'groceries',
      'shopping',
      'doctor',
      'appointment',
      'dentist',
      'gym',
      'exercise',
      'workout',
      'family',
      'friend',
      'birthday',
      'anniversary',
      'vacation',
      'travel',
      'hobby',
      'personal',
      'home',
      'house',
      'cleaning',
      'laundry',
      'cooking',
      'meal',
      'dinner',
      'lunch',
      'breakfast',
      'health',
      'medical',
      'pharmacy',
      'bank',
      'finance',
      'bills',
      'insurance',
      'car',
      'maintenance',
      'repair',
    ],
    school: [
      'assignment',
      'homework',
      'study',
      'exam',
      'test',
      'quiz',
      'class',
      'lecture',
      'professor',
      'teacher',
      'student',
      'school',
      'university',
      'college',
      'course',
      'semester',
      'grade',
      'paper',
      'essay',
      'research',
      'thesis',
      'dissertation',
      'lab',
      'laboratory',
      'textbook',
      'library',
      'campus',
      'tuition',
      'scholarship',
      'degree',
      'major',
      'minor',
      'graduation',
      'academic',
      'education',
    ],
  },

  CONFIDENCE_SCORES: {
    BASE: 0.5,
    YEAR_BONUS: 0.2,
    MONTH_BONUS: 0.2,
    DAY_BONUS: 0.2,
    HOUR_BONUS: 0.1,
    MINUTE_BONUS: 0.1,
    PRIORITY_HIGH: 0.8,
    PRIORITY_MEDIUM: 0.7,
    PRIORITY_LOW: 0.8,
    CATEGORY_HIGH: 0.8,
    CATEGORY_MEDIUM: 0.6,
    CATEGORY_LOW: 0.4,
    AMBIGUOUS_DATE: 0.6,
    NEXT_WEEK: 0.8,
    END_OF_MONTH: 0.7,
    MINIMUM: 0.3,
  },

  DATE_RANGES: {
    NEXT_WEEK_START: 7,
    NEXT_WEEK_END: 14,
    END_OF_MONTH_DAYS_BACK: 4,
  },

  PATTERNS: {
    END_OF_MONTH: /(end of (?:the )?month)/gi,
    NEXT_WEEK: /next week/i,
    TIME_FORMAT: /^(\d{1,2}):(\d{2})$/,
    TITLE_CLEANUP: /\s+/g,
    LEADING_TRAILING_CLEANUP: /^[,\s\-:]+|[,\s\-:]+$/g,
    PREPOSITION_CLEANUP: /^(by|for|at)\s+/gi,
  },
} as const;
