version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: taskoro-postgres
    environment:
      POSTGRES_DB: taskoro
      POSTGRES_USER: taskoro_user
      POSTGRES_PASSWORD: taskoro_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
