version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: taskiro-postgres
    environment:
      POSTGRES_DB: taskiro
      POSTGRES_USER: taskiro_user
      POSTGRES_PASSWORD: taskiro_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
